# -*- coding: utf-8 -*-
"""App, LifeIns

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ehywKiy5bbgHPbwqt50Mof3yJoQI6-sd
"""

import streamlit as st
import pandas as pd
import numpy as np
import io
import math
import sympy as sp
from scipy import integrate as sci_integrate

# ── Page config ───────────────────────────────────────────────────────────────
st.set_page_config(page_title="Life Insurance Pricing Engine", page_icon="📋", layout="centered")
st.title("📋 Life Insurance Pricing Engine")
st.subtitle("By Robert Luke, GitHub: X-RL9")
st.subtitle("Disclaimer: This is not financial advice!")

# ── Pre-load mortality tables ─────────────────────────────────────────────────
@st.cache_data
def load_lx_tables():
    xl = pd.read_excel('2002 mortality_tables single lives.xlsx', sheet_name=None, header=2)
    lx_tables = {}
    for name, df in xl.items():
        df = df.dropna(subset=['x'])
        df['x'] = df['x'].astype(int)
        lx_tables[name] = dict(zip(df['x'], df['lx']))
    return lx_tables

lx_tables = load_lx_tables()
ELT15_Males   = lx_tables['ELT15 Males']
ELT15_Females = lx_tables['ELT15 Females']
AM92          = lx_tables['AM92']
PMA92C        = lx_tables['PMA92C']
PFA92C        = lx_tables['PFA92C']
table_names   = list(lx_tables.keys())

# ─────────────────────────────────────────────────────────────────────────────
# ── 1. Discount ───────────────────────────────────────────────────────────────
def v(i, n):
    return 1 / ((1 + i) ** n)

# ── 2. Numeric methods ────────────────────────────────────────────────────────
def summation(f, lower, upper):
    return sum(f(k) for k in range(lower, upper + 1))

def simpson(f, lower, upper, n=1000):
    if n % 2 != 0:
        n += 1
    h = (upper - lower) / n
    total = f(lower) + f(upper)
    for k in range(1, n):
        if k % 2 == 0:
            total += 2 * f(lower + k * h)
        else:
            total += 4 * f(lower + k * h)
    return (h / 3) * total

# ── 3. Life table ─────────────────────────────────────────────────────────────
def l(x, table):
    return table[int(x)]

def tpx(t, x, table):
    return l(x + t, table) / l(x, table)

def kqx(k, x, table):
    return tpx(k, x, table) - tpx(k + 1, x, table)

def mu(x, t, table):
    age = int(x + t)
    age = min(age, max(table) - 1)
    l_prev = l(age - 1, table) if age > min(table) else l(age, table)
    l_curr = l(age, table)
    l_next = l(age + 1, table)
    if l_curr == 0:
        return 0.0
    return (l_prev - l_next) / (2 * l_curr)

# ── 4. Single life assurance ──────────────────────────────────────────────────
def Whole_eoy(x, i, table):
    upper = max(table.keys()) - x - 1
    term  = lambda k: v(i, k + 1) * kqx(k, x, table)
    return summation(term, lower=0, upper=upper)

def Whole_imm(x, i, table):
    b = max(table.keys()) - x - 1
    return simpson(lambda k: v(i, k + 1) * tpx(k, x, table) * mu(x, k, table), lower=0, upper=b)

def Term_eoy(x, n, i, table):
    term = lambda k: v(i, k + 1) * kqx(k, x, table)
    return summation(term, lower=0, upper=n - 1)

def Term_imm(x, n, i, table):
    return simpson(lambda k: v(i, k + 1) * tpx(k, x, table) * mu(x, k, table), lower=0, upper=n - 1)

def Pure(x, n, i, table):
    return v(i, n) * tpx(n, x, table)

def Endow_eoy(x, n, i, table):
    return Term_eoy(x, n, i, table) + Pure(x, n, i, table)

def Endow_imm(x, n, i, table):
    return Term_imm(x, n, i, table) + Pure(x, n, i, table)

# ── 5. Single life annuities ──────────────────────────────────────────────────
def dot_dot_a(x, i, table):
    return (1 - Whole_eoy(x, i, table)) / (i / (1 + i))

def no_dot_a(x, i, table):
    return dot_dot_a(x, i, table) - 1

def bar_a(x, i, table):
    b = max(table.keys()) - x - 1
    return simpson(lambda k: v(i, k + 1) * tpx(k, x, table), lower=0, upper=b)

def dot_dot_t(x, n, i, table):
    return (1 - Term_eoy(x, n, i, table)) / (i / (1 + i))

def no_dot_t(x, n, i, table):
    return dot_dot_t(x, n, i, table) - 1

def bar_t(x, n, i, table):
    return simpson(lambda k: v(i, k + 1) * tpx(k, x, table), lower=0, upper=n)

# ── M-thly paid annuities ─────────────────────────────────────────────────────
def m_dot_dot_a(x, m, i, table):
    """Whole life annuity due, paid m-thly."""
    annuity   = dot_dot_a(x, i, table)
    woolhouse = (m - 1) / (2 * m)
    return annuity - woolhouse

def m_no_dot_a(x, m, i, table):
    """Whole life annuity immediate, paid m-thly."""
    annuity   = no_dot_a(x, i, table)
    woolhouse = (m - 1) / (2 * m)
    return annuity + woolhouse

def m_dot_dot_t(x, n, m, i, table):
    """Term annuity due, paid m-thly."""
    annuity   = dot_dot_t(x, n, i, table)
    woolhouse = (m - 1) / (2 * m)
    nex       = Pure(x, n, i, table)
    return annuity - woolhouse * (1 - nex)

def m_no_dot_t(x, n, m, i, table):
    """Term annuity immediate, paid m-thly."""
    annuity   = no_dot_t(x, n, i, table)
    woolhouse = (m - 1) / (2 * m)
    nex       = Pure(x, n, i, table)
    return annuity + woolhouse * (1 - nex)

# ── 6. Joint life probabilities ───────────────────────────────────────────────
def tpxy(t, x, table1, y, table2):
    return tpx(t, x, table1) * tpx(t, y, table2)

def kqxy(k, x, y, table1, table2):
    kqx_ = tpx(k, x, table1) - tpx(k + 1, x, table1)
    kqy_ = tpx(k, y, table2) - tpx(k + 1, y, table2)
    return kqx_ + kqy_ - kqx_ * kqy_

def muxy(x, y, t, table1, table2):
    return mu(x, t, table1) + mu(y, t, table2)

# ── 7. Joint life assurance ───────────────────────────────────────────────────
def Whole_eoy_joint(x, y, i, table1, table2):
    upper = min(max(table1.keys()) - x, max(table2.keys()) - y) - 1
    term  = lambda k: v(i, k + 1) * kqxy(k, x, y, table1, table2)
    return summation(term, lower=0, upper=upper)

def Whole_imm_joint(x, y, i, table1, table2):
    b = min(max(table1.keys()) - x, max(table2.keys()) - y) - 1
    return simpson(lambda k: v(i, k + 1) * tpxy(k, x, table1, y, table2) * muxy(x, y, k, table1, table2), lower=0, upper=b)

def Term_eoy_joint(x, y, n, i, table1, table2):
    term = lambda k: v(i, k + 1) * kqxy(k, x, y, table1, table2)
    return summation(term, lower=0, upper=n - 1)

def Term_imm_joint(x, y, n, i, table1, table2):
    return simpson(lambda k: v(i, k + 1) * tpxy(k, x, table1, y, table2) * muxy(x, y, k, table1, table2), lower=0, upper=n - 1)

def Pure_joint(x, y, n, i, table1, table2):
    return v(i, n) * tpxy(n, x, table1, y, table2)

def Endow_eoy_joint(x, y, n, i, table1, table2):
    return Term_eoy_joint(x, y, n, i, table1, table2) + Pure_joint(x, y, n, i, table1, table2)

def Endow_imm_joint(x, y, n, i, table1, table2):
    return Term_imm_joint(x, y, n, i, table1, table2) + Pure_joint(x, y, n, i, table1, table2)

# ── 8. Joint life annuities ───────────────────────────────────────────────────
def dot_dot_a_joint(x, y, i, table1, table2):
    return (1 - Whole_eoy_joint(x, y, i, table1, table2)) / (i / (1 + i))

def no_dot_a_joint(x, y, i, table1, table2):
    return dot_dot_a_joint(x, y, i, table1, table2) - 1

def bar_a_joint(x, y, i, table1, table2):
    b = min(max(table1.keys()) - x, max(table2.keys()) - y) - 1
    return simpson(lambda k: v(i, k + 1) * tpxy(k, x, table1, y, table2), lower=0, upper=b)

def dot_dot_t_joint(x, y, n, i, table1, table2):
    return (1 - Term_eoy_joint(x, y, n, i, table1, table2)) / (i / (1 + i))

def no_dot_t_joint(x, y, n, i, table1, table2):
    return dot_dot_t_joint(x, y, n, i, table1, table2) - 1

def bar_t_joint(x, y, n, i, table1, table2):
    return simpson(lambda k: v(i, k + 1) * tpxy(k, x, table1, y, table2), lower=0, upper=n)

# ── 9. Benefit ────────────────────────────────────────────────────────────────
def benefit(x, i, table, sum_assured, benefit_type, n=None, y=None, table2=None):
    if benefit_type == 'whole_eoy':
        A = Whole_eoy(x, i, table)
    elif benefit_type == 'whole_imm':
        A = Whole_imm(x, i, table)
    elif benefit_type == 'term_eoy':
        A = Term_eoy(x, n, i, table)
    elif benefit_type == 'term_imm':
        A = Term_imm(x, n, i, table)
    elif benefit_type == 'endow_eoy':
        A = Endow_eoy(x, n, i, table)
    elif benefit_type == 'endow_imm':
        A = Endow_imm(x, n, i, table)
    elif benefit_type == 'pure':
        A = Pure(x, n, i, table)
    elif benefit_type == 'whole_eoy_joint':
        A = Whole_eoy_joint(x, y, i, table, table2)
    elif benefit_type == 'whole_imm_joint':
        A = Whole_imm_joint(x, y, i, table, table2)
    elif benefit_type == 'term_eoy_joint':
        A = Term_eoy_joint(x, y, n, i, table, table2)
    elif benefit_type == 'term_imm_joint':
        A = Term_imm_joint(x, y, n, i, table, table2)
    elif benefit_type == 'endow_eoy_joint':
        A = Endow_eoy_joint(x, y, n, i, table, table2)
    elif benefit_type == 'pure_joint':
        A = Pure_joint(x, y, n, i, table, table2)
    else:
        raise ValueError(f"Unknown benefit_type: '{benefit_type}'")
    return sum_assured * A

# ── 10. Premium ───────────────────────────────────────────────────────────────
def premium(x, i, table, sum_assured, benefit_type, annuity_type, n=None, y=None, table2=None, table_name=None, table2_name=None, m=1):
    A = benefit(x, i, table, sum_assured, benefit_type, n=n, y=y, table2=table2)
    ann = None
    
    if y is None:
        if annuity_type == 'due':
            ann = dot_dot_a(x, i, table)
        elif annuity_type == 'immediate':
            ann = no_dot_a(x, i, table)
        elif annuity_type == 'continuous':
            ann = bar_a(x, i, table)
        elif annuity_type == 'term_due':
            ann = dot_dot_t(x, n, i, table)
        elif annuity_type == 'term_immediate':
            ann = no_dot_t(x, n, i, table)
        elif annuity_type == 'term_continuous':
            ann = bar_t(x, n, i, table)
        elif annuity_type == 'm_due':
            ann = m_dot_dot_a(x, 12, i, table)
        elif annuity_type == 'm_immediate':
            ann = m_no_dot_a(x, 12, i, table)
        elif annuity_type == 'm_term_due':
            ann = m_dot_dot_t(x, n, 12, i, table)
        elif annuity_type == 'm_term_immediate':
            ann = m_no_dot_t(x, n, 12, i, table)
        elif annuity_type == 'q_due':
            ann = m_dot_dot_a(x, 4, i, table)
        elif annuity_type == 'q_immediate':
            ann = m_no_dot_a(x, 4, i, table)
        else:
            raise ValueError(f"Unknown annuity_type: '{annuity_type}'")

    else:
        if annuity_type == 'due':
            ann = dot_dot_a_joint(x, y, i, table, table2)
        elif annuity_type == 'immediate':
            ann = no_dot_a_joint(x, y, i, table, table2)
        elif annuity_type == 'continuous':
            ann = bar_a_joint(x, y, i, table, table2)
        elif annuity_type == 'term_due':
            ann = dot_dot_t_joint(x, y, n, i, table, table2)
        elif annuity_type == 'term_immediate':
            ann = no_dot_t_joint(x, y, n, i, table, table2)
        elif annuity_type == 'term_continuous':
            ann = bar_t_joint(x, y, n, i, table, table2)
        else:
            raise ValueError(f"Unknown annuity_type: '{annuity_type}'")

    return A / ann
# ─────────────────────────────────────────────────────────────────────────────

# ── Benefit type options ──────────────────────────────────────────────────────
BENEFIT_OPTIONS = {
    'Whole Life End of Year':       'whole_eoy',
    'Whole Life Immediate':         'whole_imm',
    'Term Life End of Year':        'term_eoy',
    'Term Life Immediate':          'term_imm',
    'Endowment End of Year':        'endow_eoy',
    'Endowment Immediate':          'endow_imm',
    'Pure Endowment':               'pure',
}

BENEFIT_OPTIONS_JOINT = {
    'Whole Life End of Year':       'whole_eoy_joint',
    'Whole Life Immediate':         'whole_imm_joint',
    'Term Life End of Year':        'term_eoy_joint',
    'Term Life Immediate':          'term_imm_joint',
    'Endowment End of Year':        'endow_eoy_joint',
    'Endowment Immediate':          'endow_imm_joint',
    'Pure Endowment':               'pure_joint',
}

ANNUITY_OPTIONS = {
    'Annually in Advance (Due)':        'due',
    'Annually in Arrear (Immediate)':   'immediate',
    'Continuously':                     'continuous',
    'Term - Annually in Advance':       'term_due',
    'Term - Annually in Arrear':        'term_immediate',
    'Term - Continuously':              'term_continuous',
    'Monthly in Advance':               'm_due',
    'Monthly in Arrear':                'm_immediate',
    'Term - Monthly in Advance':        'm_term_due',
    'Term - Monthly in Arrear':         'm_term_immediate',
    'Quarterly in Advance':             'q_due',
    'Quarterly in Arrear':              'q_immediate',
}

# ── UI ────────────────────────────────────────────────────────────────────────
st.header("1. Policy Details")

policy_type  = st.selectbox("Number of Lives", ["Single Life", "Joint Life"])
benefit_label  = st.selectbox("Benefit Type", list(BENEFIT_OPTIONS.keys()))
annuity_label  = st.selectbox("Premium Payment", list(ANNUITY_OPTIONS.keys()))

# ── Frequency selector (only shown for m-thly options) ───────────────────────
if 'Monthly' in annuity_label:
    m = 12
elif 'Quarterly' in annuity_label:
    m = 4
else:
    m = 1

sum_assured    = st.number_input("Sum Assured (£)", min_value=1000, value=100000, step=1000)
i              = st.number_input("Interest Rate", min_value=0.001, max_value=0.20, value=0.04, step=0.001, format="%.3f")

st.header("2. Life Details")
col1, col2 = st.columns(2)

with col1:
    st.subheader("Life 1")
    x          = st.number_input("Age (x)", min_value=0, max_value=120, value=50)
    table_name = st.selectbox("Mortality Table", table_names, key='t1')
    table      = lx_tables[table_name]

if policy_type == "Joint Life":
    with col2:
        st.subheader("Life 2")
        y           = st.number_input("Age (y)", min_value=0, max_value=120, value=47)
        table2_name = st.selectbox("Mortality Table", table_names, key='t2')
        table2      = lx_tables[table2_name]
    benefit_type = BENEFIT_OPTIONS_JOINT[benefit_label]
else:
    y = None
    table2 = None
    table2_name = None
    benefit_type = BENEFIT_OPTIONS[benefit_label]

annuity_type = ANNUITY_OPTIONS[annuity_label]

has_term = any(b in benefit_type for b in ['term', 'endow', 'pure'])
if has_term:
    n = st.number_input("Term (years)", min_value=1, max_value=60, value=20)
else:
    n = None

# ── Results ───────────────────────────────────────────────────────────────────
st.header("3. Results")
if st.button("Calculate Premium", type="primary"):
    try:
        P = premium(
            x=x, i=i, table=table,
            sum_assured=sum_assured,
            benefit_type=benefit_type,
            annuity_type=annuity_type,
            n=n, y=y, table2=table2,
            table_name=table_name,
            table2_name=table2_name,
            m=m
        )

        col3, col4 = st.columns(2)
        with col3:
            st.metric("Net Annual Premium", f"£{P:,.2f}")
        with col4:
            st.metric("Sum Assured", f"£{sum_assured:,.2f}")

        st.success(f"✅ Net Annual Premium: £{P:,.2f}")

    except Exception as e:
        st.error(f"Error: {e}")
