# -*- coding: utf-8 -*-
"""App, LifeIns

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ehywKiy5bbgHPbwqt50Mof3yJoQI6-sd
"""

pip install streamlit

import streamlit as st
import pandas as pd
import io
import math

# ── Page config ──────────────────────────────────────────────────────────────
st.set_page_config(page_title="Life Insurance Pricing Engine", page_icon="📋", layout="centered")
st.title("📋 Life Insurance Pricing Engine")

# ── Upload mortality tables ───────────────────────────────────────────────────
st.sidebar.header("1. Upload Mortality Tables")
uploaded_file = st.sidebar.file_uploader("Upload your .xlsx mortality table file", type="xlsx")

if uploaded_file:
    file_bytes = uploaded_file.read()

    def load_lx_tables(file_bytes):
        xl = pd.read_excel(io.BytesIO(file_bytes), sheet_name=None, header=2)
        lx_tables = {}
        for name, df in xl.items():
            df = df.dropna(subset=['x'])
            df['x'] = df['x'].astype(int)
            lx_tables[name] = dict(zip(df['x'], df['lx']))
        return lx_tables

    lx_tables = load_lx_tables(file_bytes)
    table_names = list(lx_tables.keys())
    st.sidebar.success(f"✅ Loaded: {', '.join(table_names)}")

    # ── Paste all your functions here ─────────────────────────────────────────
    # v, l, tpx, kqx, mu, summation, simpson
    # Whole_eoy, Whole_imm, Term_eoy, Term_imm, Endow_eoy, Endow_imm, Pure
    # Whole_eoy_joint, Term_eoy_joint, etc.
    # dot_dot_a, no_dot_a, bar_a, dot_dot_t, no_dot_t, bar_t
    # dot_dot_a_joint, etc.
    # benefit, premium

    # ── Policy inputs ─────────────────────────────────────────────────────────
    st.header("2. Policy Details")

    col1, col2 = st.columns(2)
    with col1:
        policy_type = st.selectbox("Number of Lives", ["Single Life", "Joint Life"])
        benefit_type = st.selectbox("Benefit Type", [
            'whole_eoy', 'whole_imm',
            'term_eoy', 'term_imm',
            'endow_eoy', 'endow_imm',
            'pure'
        ])
        annuity_type = st.selectbox("Premium Payment", [
            'due', 'immediate', 'continuous',
            'term_due', 'term_immediate', 'term_continuous'
        ])

    with col2:
        sum_assured = st.number_input("Sum Assured (£)", min_value=1000, value=100000, step=1000)
        i = st.number_input("Interest Rate", min_value=0.001, max_value=0.20, value=0.04, step=0.001, format="%.3f")

    st.header("3. Life Details")
    col3, col4 = st.columns(2)
    with col3:
        st.subheader("Life 1")
        x = st.number_input("Age (x)", min_value=0, max_value=120, value=50)
        table_name = st.selectbox("Mortality Table", table_names, key='table1')
        table = lx_tables[table_name]

    if policy_type == "Joint Life":
        with col4:
            st.subheader("Life 2")
            y = st.number_input("Age (y)", min_value=0, max_value=120, value=47)
            table2_name = st.selectbox("Mortality Table", table_names, key='table2')
            table2 = lx_tables[table2_name]
            benefit_type = benefit_type + '_joint'
            annuity_type_joint = annuity_type
    else:
        y = None
        table2 = None
        table2_name = None

    has_term = any(x in benefit_type for x in ['term', 'endow', 'pure'])
    if has_term:
        n = st.number_input("Term (years)", min_value=1, max_value=60, value=20)
    else:
        n = None

    # ── Calculate ─────────────────────────────────────────────────────────────
    st.header("4. Results")
    if st.button("Calculate Premium", type="primary"):
        try:
            P = premium(
                x=x, i=i, table=table,
                sum_assured=sum_assured,
                benefit_type=benefit_type,
                annuity_type=annuity_type,
                n=n, y=y, table2=table2,
                table_name=table_name,
                table2_name=table2_name
            )

            col5, col6 = st.columns(2)
            with col5:
                st.metric("Net Annual Premium", f"£{P:,.2f}")
            with col6:
                st.metric("Sum Assured", f"£{sum_assured:,.2f}")

            st.success(f"✅ Net Annual Premium: £{P:,.2f}")

        except Exception as e:
            st.error(f"Error: {e}")

else:
    st.info("👈 Please upload your mortality tables file to get started.")