# -*- coding: utf-8 -*-
"""Life Insurance Pricing Engine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HOJ8LWgdG8XWrgVEN3ZLGLntoTMYS2NL
"""

import numpy as np
import pandas as pd
import math
import sympy as sp
from google.colab import files
import io
import sympy as sp
import math

uploaded = files.upload()

file_bytes = list(uploaded.values())[0]

from scipy import integrate as sci_integrate

def integrate(f, lower, upper):
    result, _ = sci_integrate.quad(f, lower, upper)
    return result

def summation(f, lower, upper):
    return sum(f(k) for k in range(lower, upper + 1))

def simpson(f, lower, upper, n=10):

    if n % 2 != 0:
        n += 1

    h = (upper - lower) / n

    total = f(lower) + f(upper)

    for k in range(1, n):
        if k % 2 == 0:
            total += 2 * f(lower + k * h)
        else:
            total += 4 * f(lower + k * h)

    return (h / 3) * total

def differentiate(expression: str, variable: str = 'x', order: int = 1):
    """
    Differentiate an expression.

    Args:
        expression: Math expression as a string, e.g. 'x**3 + 2*x'
        variable:   Variable to differentiate with respect to (default: 'x')
        order:      Order of differentiation (default: 1)

    Returns:
        Symbolic derivative
    """
    var = sp.Symbol(variable)
    expr = sp.sympify(expression)
    result = sp.diff(expr, var, order)
    return result

"""**Discount Function**"""

# Discounting

def v(i,n):
  return 1/((1+i)**n)

"""**Survival Function**"""

def load_lx_tables(file_bytes):
    xl = pd.read_excel(io.BytesIO(file_bytes), sheet_name=None, header=2)
    # header=2 → row 3 has the real column names (x, lx, dx, ...)

    lx_tables = {}
    for name, df in xl.items():
        df = df.dropna(subset=['x'])        # drop blank rows
        df['x'] = df['x'].astype(int)      # age as integer
        lx_tables[name] = dict(zip(df['x'], df['lx']))

    return lx_tables

lx_tables = load_lx_tables(file_bytes)

ELT15_Males   = lx_tables['ELT15 Males']
ELT15_Females = lx_tables['ELT15 Females']
AM92          = lx_tables['AM92']
PMA92C        = lx_tables['PMA92C']
PFA92C        = lx_tables['PFA92C']

# Life table values

def l(x, table):
  return table[int(x)]

l(50,AM92)

tpx(1,50,AM92)

mu(50,3,AM92)

# tpx

def tpx(t, x, table):
  return l(x+t,table)/l(x,table)

# kqx

def kqx(k,x,table):
  return tpx(k,x,table) - tpx(k+1,x,table)

# Force of mortality

def mu(x, t, table):
    age = int(x + t)
    age = min(age, max(table) - 1)

    l_prev = l(age - 1, table) if age > min(table) else l(age, table)
    l_curr = l(age, table)
    l_next = l(age + 1, table)

    if l_curr == 0:
        return 0.0

    return (l_prev - l_next) / (2 * l_curr)

"""**Single Life Assurance Benefits**"""

# Whole life immediate

def Whole_imm(x, i, table):
    b = max(table) - x - 1
    assurance = simpson(lambda k: v(i, k+1) * tpx(k, x, table) * mu(x, k, table), lower=0, upper=b)
    return assurance

# Term immediate

def Term_imm(x,n,i,table):
    b = n - 1
    assurance = simpson(lambda k: v(i, k+1) * tpx(k, x, table) * mu(x, k, table), lower=0, upper=b)
    return assurance

# Endowment immediate

def Endow_imm(x,n,i,table):
  assurance = Term_imm(x,n,i,table) + Pure(x,n,i,table)
  return assurance

# Whole life end of year

def Whole_eoy(x, i, table):
    max_age = max(table)
    upper   = max_age - x - 1
    term    = lambda k: v(i, k + 1) * kqx(k, x, table)
    return summation(term, lower=0, upper=upper)

# Term end of year

def Term_eoy(x,n,i,table):
    upper   = n - 1
    term    = lambda k: v(i, k + 1) * kqx(k, x, table)
    return summation(term, lower=0, upper=upper)

# Endowment end of year

def Endow_eoy(x,n,i,table):
  assurance = Term_eoy(x,n,i,table) + Pure(x,n,i,table)
  return assurance

# Pure endowment

def Pure(x,n,i,table):
  benefit = v(i,n)*tpx(n,x,table)
  return benefit

Whole_imm(50,0.04,AM92)

Whole_eoy(50,0.04,AM92)

Term_eoy(50,20,0.04,AM92)

"""**Single Life Annuities**"""

# Annuity due
def dot_dot_a(x,i,table):
  return (1-Whole_eoy(x,i,table))/((i)/(1+i))

# Annuity immediate
def no_dot_a(x,i,table):
  return dot_dot_a(x,i,table) - 1

# Annuity continuous
def bar_a(x,i,table):
    b = max(table) - x - 1
    annuity = simpson(lambda k: v(i, k+1) * tpx(k, x, table) , lower=0, upper=b)
    return annuity

# Term annuity due
def dot_dot_t(x,n,i,table):
  return (1-Term_eoy(x,n,i,table))/((i)/(1+i))

# Term annuity immediate
def no_dot_t(x,n,i,table):
  return dot_dot_t(x,n,i,table) - 1

# Term annuity continuous
def bar_t(x,n,i,table):
  b = n
  annuity = simpson(lambda k: v(i, k+1) * tpx(k, x, table) , lower=0, upper=b)
  return annuity

dot_dot_a(40,0.04,AM92)

no_dot_a(40,0.04,AM92)

bar_a(40,0.04,AM92)

"""**M-thly Paid Annuities**"""

# Annuity due
def m_dot_dot_a(x,m,i,table):
  annuity = dot_dot_a(x,i,table)
  Woolhouse = (m-1)/2*m
  return annuity - Woolhouse

# Annuity immediate
def m_no_dot_a(x,m,i,table):
  annuity = no_dot_a(x,i,table)
  Woolhouse = (m-1)/2*m
  return annuity + Woolhouse

# Term annuity due
def m_dot_dot_t(x,n,m,i,table):
  annuity = dot_dot_t(x,n,i,table)
  Woolhouse = (m-1)/2*m
  nex = pure(x,n,i,table)
  return annuity - Woolhouse*(1-nex)

# Term annuity immediate
def m_no_dot_t(x,n,m,i,table):
  annuity = no_dot_t(x,n,i,table)
  Woolhouse = (m-1)/2*m
  nex = pure(x,n,i,table)
  return annuity + Woolhouse*(1-nex)

"""**Joint-Life Survival Probabilities**"""

# Joint survival probability
def tpxy(t, x, table1,y,table2):
  return tpx(t,x,table1)*tpx(t,y,table2)

# Joint death probability
def tqxy(t, x, table1,y,table2):
  a = 1 - tpx(t,x,table1)
  b = 1 - tpx(t,y,table2)
  joint = a*b
  return a + b - joint

# For discrete functions
def kqxy(k, x, y, table1, table2):
    kqx_ = tpx(k, x, table1) - tpx(k+1, x, table1)
    kqy_ = tpx(k, y, table2) - tpx(k+1, y, table2)
    return kqx_ + kqy_ - kqx_ * kqy_

# Joint force of mortality
def muxy(x,y,t,table1,table2):
  return mu(x,t,table1) + mu(y,t,table2)

"""**Joint-Life Insurance Benefits**"""

# Whole life immediate

def Whole_imm(x,y,i,table1,table2):
    b = max(max(table1,table2)) - x - 1
    assurance = simpson(lambda k: v(i, k+1) * tpxy(k, x, table1,y,table2) * muxy(x,y, k, table1,table2), lower=0, upper=b)
    return assurance

# Term immediate

def Term_imm(x,y,n,i,table1,table2):
    b = max(max(table1,table2)) - x - 1
    assurance = simpson(lambda k: v(i, k+1) * tpxy(k, x, table1,y,table2) * muxy(x,y, k, table1,table2), lower=0, upper=b)
    return assurance

# Endowment immediate

def Endow_imm(x,y,n,i,table1,table2):
  assurance = Term_imm(x,y,n,i,table1,table2) + Pure(x,y,n,i,table1,table2)
  return assurance

# Whole life end of year

def Whole_eoy(x,y,i,table1,table2):
    max_age = max(max(table1,table2))
    upper   = max_age - x - 1
    term    = lambda k: v(i, k + 1) * kqxy(k, x, y, table1, table2)
    return summation(term, lower=0, upper=upper)

# Term end of year

def Term_eoy(x,y,n,i,table1,table2):
    upper   = n - 1
    term    = lambda k: v(i, k + 1) * kqxy(k, x, y, table1, table2)
    return summation(term, lower=0, upper=upper)

# Endowment end of year

def Endow_eoy(x,y,n,i,table1,table2):
  assurance = Term_eoy(x,y,n,i,table1,table2) + Pure(x,y,n,i,table1,table2)
  return assurance

# Pure endowment

def Pure(x,y,n,i,table1,table2):
  benefit = v(i,n)*tpxy(n,x,table1,y,table2)
  return benefit

"""**Joint-Life Annuities**"""

# Annuity due
def dot_dot_a(x,y,i,table1,table2):
  return (1-Whole_imm(x,y,i,table1,table2))/((i)/(1+i))

# Annuity immediate
def no_dot_a(x,y,i,table1,table2):
  return dot_dot_a(x,y,i,table1,table2) - 1

# Annuity continuous
def bar_a(x,y,i,table1,table2):
    b = max(max(table1,table2)) - x - 1
    annuity = simpson(lambda k: v(i, k+1) * tpxtpxy(k,x,table1,y,table2) , lower=0, upper=b)
    return annuity

# Term annuity due
def dot_dot_t(x,y,n,i,table1,table2):
  return (1-Term_eoy(x,y,n,i,table1,table2))/((i)/(1+i))

# Term annuity immediate
def no_dot_t(x,y,n,i,table1,table2):
  return dot_dot_t(x,y,n,i,table1,table2) - 1

# Term annuity continuous
def bar_t(x,y,n,i,table1,table2):
  b = n
  annuity = simpson(lambda k: v(i, k+1) * tpxtpxy(k,x,table1,y,table2) , lower=0, upper=b)
  return annuity





"""**Second Death Probabilities**"""

